import type { Metadata } from "next";
import { Inter } from "next/font/google";
import './globals.css';
import { Navbar } from 'components/layout/navbar';
import { GeistSans } from 'geist/font/sans';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={GeistSans.variable}>
      <body className="bg-neutral-50 text-black selection:bg-teal-300 dark:bg-neutral-900 dark:text-white dark:selection:bg-pink-500 dark:selection:text-white">
          <Navbar />
          <main>
          </main>
      </body>
    </html>
  );
}
